### ISSUE TITLE
Command injection vulnerbility

### ISSUE THREAD

**Issue by Artoria2e5** [varnav/makejxl#1]
The current code calls cjxl as a stitched-together shell command, and that's not safe: a filename with a semicolon in it would just create a second command.

You might ask about quoting, but the issue is the different default shells (cmd and sh) have different quoting methods.

I am on a phone right now, but the gist is to replace
```py
convert_cmd = f'cjxl --quiet -s {speed} --num_threads={jobs} {fp} {newpath}'
conversion_return_code = run(convert_cmd, shell=True).returncode
```
with
```py
convert_cmd = ['cjxl', '--quiet', '-s', speed, f'--num_threads={jobs}', fp, newpath]
conversion_return_code = run(convert_cmd).returncode
```

(It would be nice to add a `'--',` before fp so the program does not recognize a name starting with `-` as some invalid option, but i can't check if cjxl takes that yet.)

**Comment by varnav** [comment]
Fixed.
But it was a low risk, basically you're running it from CLI already, with same permissions. Injection can be made, but pretty pointless.

**Comment by Artoria2e5** [comment]
shlex.split fixes the injection but not the misbehavior on whitespace-containing filenames, since you are still doing a shell-like pass on the input fp string. You can shlex.quote the two filenames if you are so inclined, but why that when you can just use a list…

**Comment by varnav** [comment]
Ok, I agree, it's better. I will need to do some testing first.

**Comment by varnav** [comment]
Ok should be good now.
Thank you!
