### ISSUE TITLE
I am just trying to encode JPEG to JXL

### ISSUE THREAD

**Issue by MartinEesmaa** [varnav/makejxl#2]
Hello! I tried to follow these steps, but when I typed: makejxl.exe "c:\\Users\\username\\Pictures\\My Vacation" its example folder and I got a error:
cjxl not found
Traceback (most recent call last):
  File "makejxl.py", line 86, in <module>
    main()
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "makejxl.py", line 44, in main
    exit(1)
NameError: name 'exit' is not defined
[30220] Failed to execute script makejxl

I already downloaded the cjxl, where do I put cjxl for path environment?
Please help me, @varnav !

Regards
- Martin Eesmaa

**Comment by varnav** [comment]
Copy cjxl to `%USERPROFILE%\AppData\Local\Microsoft\WindowsApps` - this directory is in path.

**Comment by MartinEesmaa** [comment]
How, @varnav? I just already copied cjxl that you gave me directory path?

MAKEJXL Folder:
![MAKEJXLFOLDER](https://user-images.githubusercontent.com/88035011/131756265-d8fa0569-2d28-4b50-aa5a-f0e1b20f2f09.png)

WindowsApps Folder:
<img width="960" alt="windowsappsproblemjxl" src="https://user-images.githubusercontent.com/88035011/131756310-2556ecad-3e1f-4adf-973e-930588f8e7ff.png">

- Martin Eesmaa

**Comment by varnav** [comment]
You need `cjxl.exe`

It will be inside `local64\bin-global` folder after you build it. To build you need to run `media-autobuild_suite.bat` first.

**Comment by MartinEesmaa** [comment]
EDIT: Sorry, that I went wrong of cjxl set quality 100, but I set 40, so it's working thanks.

Is that JPEG XL is better than AVIF or AVIF better than JPEG XL, @varnav ?

**Comment by varnav** [comment]
There's series of articles on this. It's not just about file size:

https://cloudinary.com/blog/what_to_focus_on_in_image_compression_fidelity_or_appeal

Also jpeg to jpeg xl conversion is lossless and reversible.

**Comment by MartinEesmaa** [comment]
Okay, I will close this issue! Thanks, @varnav!
